# Generated by Django 3.2.3 on 2025-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=('Максимально допустимое число знаков - ', '255.'), max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(help_text=('Максимально допустимое число знаков - ', '1000.'), max_length=1000, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Укажите цену', verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
    ]
