# Generated by Django 3.2.3 on 2025-02-24 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20250218_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.PositiveBigIntegerField(default=1, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Счет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_by_product', to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
