# Generated by Django 3.2.3 on 2025-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250228_0022'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating_user_product',
        ),
        migrations.AddConstraint(
            model_name='productproperty',
            constraint=models.UniqueConstraint(fields=('product', 'property'), name='unique_product_property'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_rating_user_product'),
        ),
    ]
