# Generated by Django 3.2.3 on 2025-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250301_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
