# Generated by Django 3.2.3 on 2025-03-08 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250301_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Максимально допустимое число знаков - 32.', max_length=32, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Максимально допустимое число знаков - 32.', max_length=32, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Максимально допустимое число знаков - 32.', max_length=32, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Максимально допустимое число знаков - 32.', max_length=32, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text=('Максимально допустимое число знаков - ', '255.'), max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Укажите цену', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='Цена'),
        ),
        migrations.AlterUniqueTogether(
            name='productproperty',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category_prod', to='products.product')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category_cat', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Подкатегория продукта',
                'verbose_name_plural': 'Подкатегории продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_by_category', to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='products_by_sub_category', through='products.ProductSubCategory', to='products.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AddConstraint(
            model_name='productsubcategory',
            constraint=models.UniqueConstraint(fields=('product', 'sub_category'), name='unique_product_sub_category'),
        ),
    ]
