# Generated by Django 3.2.3 on 2025-03-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250308_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'Подкатегория продукта', 'verbose_name_plural': 'Подгатегории продуктов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=8, unique=True, verbose_name='Артикул')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_by_product', to='products.product', unique=True, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('product', 'article'), name='unique_product_article'),
        ),
    ]
