# Generated by Django 3.2.3 on 2025-03-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250305_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_favorite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_in_shopping_cart',
        ),
    ]
