# Generated by Django 3.2.3 on 2025-03-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250312_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_by_sub_category', to='products.subcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductSubCategory',
        ),
    ]
