# Generated by Django 3.2.3 on 2025-03-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250313_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_by_product', to='products.product', verbose_name='Продукт'),
        ),
    ]
