# Generated by Django 3.2 on 2025-03-14 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_alter_article_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_by_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text=('Максимально допустимое число знаков - ', '1000.'), max_length=1000, validators=[django.core.validators.MinLengthValidator(1000)], verbose_name='Описание'),
        ),
    ]
