# Generated by Django 3.2 on 2025-03-14 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250314_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text=('Максимально допустимое число знаков - ', '1000.'), max_length=1000, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание'),
        ),
    ]
