# Generated by Django 3.2 on 2025-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PcDIY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ('ПК сборка',),
                'verbose_name_plural': ('ПК сборки',),
            },
        ),
    ]
