# Generated by Django 3.2 on 2025-03-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_description'),
        ('make_pc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcdiy',
            name='cpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_by_product', to='products.product', unique=True, verbose_name='Процессор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='gpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_by_product', to='products.product', unique=True, verbose_name='Видеокарта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='hdd_storage_memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hdd_by_product', to='products.product', verbose_name='HDD накопитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='motherboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_by_product', to='products.product', unique=True, verbose_name='Материнская плата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='pc_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pc_box_by_product', to='products.product', unique=True, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='power_supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_by_product', to='products.product', unique=True, verbose_name='Блок питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='ram_memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ram_by_product', to='products.product', verbose_name='Оперативная память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcdiy',
            name='ssd_storage_memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ssd_by_product', to='products.product', verbose_name='SSD накопитель'),
            preserve_default=False,
        ),
    ]
