# Generated by Django 3.2 on 2025-03-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_description'),
        ('make_pc', '0002_auto_20250316_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcdiy',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_by_product', to='products.product', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='pcdiy',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_by_product', to='products.product', verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='pcdiy',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_by_product', to='products.product', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='pcdiy',
            name='pc_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_box_by_product', to='products.product', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='pcdiy',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_by_product', to='products.product', verbose_name='Блок питания'),
        ),
    ]
