# GENERAL
LONG_STR_CUT_VALUE = 15

# CATEGORY
CATEGORY_NAME_MAX_LENGTH = 32
CATEGORY_SLUG_MAX_LENGTH = 32

# PRODUCTS
MIN_PRICE_VALUE = 1
MAX_PRICE_VALUE = 1_000_000_000
MAX_NAME_LENGTH = 255
MIN_NAME_LENGTH = 5
MAX_VALUE_LENGTH = 255
MAX_DESCRIPTION_LENGTH = 1000
MIN_DESCRIPTION_LENGTH = 5
DEFAULT_RATING = 0
DEFAULT_ARTICLE_DIGIT = '100001'

# ERR MESSAGES
RATING_ALREADY_EXIST = 'Вы уже оценили данный продукт'
FAVORITE_ALREADY_EXIST = 'Этот продукт уже в избранном.'
SHOPPING_CART_ALREADY_EXIST = 'Этот продукт уже в корзине.'
PRICE_ERR_MSG = 'Стоимость товара не может быть менее 1 (еденицы).'
PRODUCT_NAME_ERR_MSG = 'Длина поля name не должна превышать {} знаков.'
