# PRODUCTS
PRICE_ERR_MSG = 'Стоимость товара не может быть менее 1 (еденицы)'
MIN_PRODUCT_PRICE = 1
MAX_NAME_LENGTH = 255
MAX_VALUE_LENGTH = 255
MAX_DESCRIPTION_LENGTH = 1000
DEFAULT_RATING = 0
LONG_STR_CUT_VALUE = 15
